export const fruitDetails = [
    {
        id: 1,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 2,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 3,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 4,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 5,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 6,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 7,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 8,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 9,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 10,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 11,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 12,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
    {
        id: 13,
        name: "Awa",
        color: "Morado",
        power: "Invisibilidad",
        eater: "Bolkar",
        type: "Tipopo",
        image: "https://drive.google.com/uc?export=view&id=1qVFnMX9QFFMAGTT142PX48T9j8ZyQ-bd",
        description_card: "Loren ipsum loren",
        description_fruit:
            "Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo Esta es una fruta magnifica traida del congo",
    },
];
